# You can specify this in your variables. If undefined, an interface
# which name starts with "wl" will be used â€“ if any.
#wireless_interface: wlan0

# G5-CCH / 5 900 MHz / CH 180 allows 33 dBm
wireless_ocb_frequency: 5900
wireless_ocb_width: 10
